const baseFirstPeriods = [
  [
    course("FBTMM01", "Matemática Básica"),
    course("FBTPS03", "Introducción a la Ingeniería"),
    course("FBTPS04", "Pensamiento Computacional"),
    course("FBTEM01", "Competencias para Emprender"),
    course("FBTLI13", "Ingles IV"),
  ],
  [
    course("BPTM01", "Matemáticas I", "FBTMM01"),
    course("FBTEC05", "Investigación y Sustentabilidad"),
    course("BPTPI07", "Diseno asistido por Computador"),
    course("BPTQI21", "Química General", "FBTMM01"),
    course("FBTLI14", "Ingles V", "FBTLI13"),
  ],
  [
    course("BPTM02", "Matemáticas II", "BPTM01"),
    course("BPTFI01", "Física I", "BPTM01"),
    course("BPTPS05", "Algoritmos y Programación", "FBTPS04"),
    course("BPTQI22", "Laboratorio de Química General", "BPTQI21", { l: 4 }),
    course("FBTEM02", "Ideas Emprendedoras"),
  ],
];

const mecanicaFirstPeriods = [
  [
    course("FBTMM01", "Matemática Básica"),
    course("FBTPS03", "Introducción a la Ingeniería"),
    course("FBTLI13", "Ingles IV"),
    course("FBTPS04", "Pensamiento Computacional"),
    course("FBTEM01", "Competencias para Emprender"),
  ],
  [
    course("BPTM01", "Matemáticas I", "FBTMM01"),
    course("BPTPI07", "Diseno asistido por Computador"),
    course("FBTLI14", "Ingles V", "FBTLI13"),
    course("BPTQI21", "Química General", "FBTMM01"),
    course("FBTHE05", "Investigación y Sustentabilidad"),
  ],
  [
    course("BPTM02", "Matemáticas II", "BPTM01"),
    course("BPTFI01", "Física I", "BPTM01"),
    course("BPTPS05", "Algoritmos y Programación", "FBTPS04"),
    course("BPTQI22", "Laboratorio de Química General", "BPTQI21", { l: 4 }),
    course("FBTEM02", "Ideas Emprendedoras"),
  ],
];

export const flowPrograms = [
  {
    id: "sistemas",
    name: "Ingeniería de Sistemas",
    approval: "Aprobado en Consejo de Escuela 2026",
    updatedAt: "20/03/2026",
    periods: [
      ...baseFirstPeriods,
      [
        course("BPTM03", "Matemáticas III", "BPTM02"),
        course("BPTFI02", "Física II", "BPTFI01+BPTM02"),
        course("BPTPS06", "Estructuras de Datos", "BPTPS05"),
        course("BPTM30", "Matemáticas Discretas", "BPTM01"),
        course("FBTHE11", "Venezuela, Identidad y Contexto"),
      ],
      [
        course("BPTM04", "Matemáticas IV", "BPTM03"),
        course("BPTFI05", "Laboratorio de Física Aplicada", "BPTFI02", { l: 4 }),
        course("FPTSP04", "Sistemas de Información", "BPTPS06"),
        course("BPTEN12", "Arquitectura del Computador", "BPTPS05"),
        course("BPTMI31", "Algebra Lineal", "BPTM03"),
      ],
      [
        course("BPTM11", "Ecuaciones Diferenciales", "BPTM04"),
        course("BPTMI06", "Estadistica para Ingenieros I", "BPTM03"),
        course("FPTSP01", "Bases de Datos I", "BPTPS06"),
        course("BPTSP03", "Organizacion del Computador", "BPTEN12"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("BPTM05", "Matemáticas V", "BPTM04"),
        course("BPTMI07", "Estadistica para Ingenieros II", "BPTMI06+BPTM03"),
        course("FPTSP26", "Bases de Datos II", "FPTSP01"),
        course("FPTSP17", "Optimización I", "BPTM11"),
        course("BPTSP04", "Sistemas Operativos", "BPTSP03"),
      ],
      [
        course("FPTPI09", "Gestion Cadena Suministro I", "FPTSP17"),
        course("BPTMM91", "Cálculo Numérico", "BPTM11"),
        course("FPTSP07", "Ingeniería de Software", "FPTSP01+FPTSP04"),
        course("FPTSP19", "Optimización II", "FPTSP17"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTSP28", "Sistemas Distribuidos", "BPTSP03"),
        course("FPTSP21", "Modelacion de Sistemas en Redes", "BPTPS06"),
        course("FPTSP20", "Simulación", "BPTMI06"),
        course("FPTM21", "Modelos Estocasticos", "BPTMI06"),
        course("FPTSP22", "Taller de Trabajo de Grado", "120 CR o 57 CBP", { a: 2, ps: 2, credits: 3 }),
      ],
      [
        course("FPTEN23", "Sistemas de Redes", "BPTFI02 o 57BP"),
        course("FPTSP27", "Analisis de Datos", "BPTMI07 o 57BP"),
        course("FPTSP23", "Sistemas de Apoyo", "BPTMI07 o 57BP"),
        course("FPS", "Seminario Profesional", "120 cr", { a: 2, ps: 2, credits: 3 }),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTSP18", "Seguridad de la Información", "FPTEN23 o 57BP"),
        course("FPTSP11", "Gerencia de Proyectos TIC", "FPTSP04 o 57BP"),
        course("FPTSP25", "Computacion Emergente", "BPTMI31 o 57 cr BP"),
        course("FPTEN27", "Robótica Industrial", "BPTPS05"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTSP14", "Proyecto de Ingeniería", "150 cr o 57cr BP"),
        course("FPTSP15", "Ingeniería Económica", "150 cr o 57 cr BP"),
        course("FPTCS16", "Ingeniería Ambiental", "150 cr o 57cr BP"),
        course("FGE", "Formacion General Electiva"),
        course("FGE", "Formacion General Electiva"),
      ],
    ],
  },
  {
    id: "civil",
    name: "Ingeniería Civil",
    approval: "Aprobado en mayo 2026",
    updatedAt: "Mayo 2026",
    periods: [
      ...baseFirstPeriods,
      [
        course("BPTM03", "Matemáticas III", "BPTM02"),
        course("BPTFI02", "Física II", "BPTFI01+BPTM02"),
        course("BPTPI02", "Mecánica I", "BPTFI01"),
        course("BPTCS01", "Topografia", "BPTPI07", { a: 3, l: 1 }),
        course("FBTHE11", "Vzla. Identidad y Contexto"),
      ],
      [
        course("BPTM04", "Matemáticas IV", "BPTM03"),
        course("BPTFI05", "Laboratorio de Física Aplicada", "BPTFI02", { l: 4 }),
        course("BPTPI04", "Mecánica de Sólidos I", "BPTPI02"),
        course("BPTM31", "Algebra Lineal", "BPTM03"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("BPTM11", "Ecuaciones Diferenciales", "BPTM04"),
        course("BPTCS02", "Materiales y Ensayos", "BPTQI21", { a: 3, ps: 1 }),
        course("BPTPI05", "Mecánica de Sólidos II", "BPTPI04"),
        course("BPTMI06", "Estadistica para Ingenieros I", "BPTM02"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("BPTM05", "Matemáticas V", "BPTM04"),
        course("FPTCS01", "Estructuras I", "BPTM31+BPTPI04+BPTPI05"),
        course("FPTCS04", "Geotecnia I", "BPTPI04"),
        course("BPTEN14", "Mecánica de Fluidos I", "BPTM04"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTCS03", "Hidraulica", "BPTEN14"),
        course("FPTCS02", "Estructuras II", "FPTCS01"),
        course("FPTCS06", "Geotecnia II", "FPTCS04"),
        course("FPTCS07", "Vias de Comunicacion I", "BPTCS01+FPTCS04"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTCS05", "Hidrologia y Drenaje Vial", "FPTCS03"),
        course("FPTCS18", "Concreto Armado I", "FPTCS02+BPTCS02"),
        course("FPTCS09", "Fundaciones y Muros", "FPTCS06"),
        course("FPTCS10", "Vias de Comunicacion II", "FPTCS07+FPTCS03"),
        course("FPTSP22", "Taller de Trabajo de Grado", "120 cred. o 57 cred BP", { a: 2, ps: 2, credits: 3 }),
      ],
      [
        course("FPTCS11", "Instalaciones para Edificios", "FPTCS03"),
        course("FPTCS19", "Concreto Armado II", "FPTCS18"),
        course("FPTCS14", "Acero", "FPTCS02+BPTCS02"),
        course("FPTCS12", "Proyectos Viales", "FPTCS10"),
        course("FPS", "Seminario Profesional I", "120 cred.", { a: 2, ps: 2, credits: 3 }),
      ],
      [
        course("FPTCS21", "Acueductos y Cloacas", "FPTCS05"),
        course("FPTCS22", "Modelos de Inform. Constructiva", "BPTPI07+FPTCS11"),
        course("FPTCS23", "Proyectos en Acero", "FPTCS14"),
        course("FPTSP24", "Gerencia de la Construccion", "FPTCS18 o 57 cred BP"),
        course("FPS3", "Seminario Profesional II", "120 cred."),
      ],
      [
        course("FPTCS16", "Ingeniería Ambiental", "150 cred. o 57 cred BP"),
        course("FPTCS20", "Proyectos en Concreto", "FPTCS18+FPTCS19"),
        course("FPTSP15", "Ingeniería Económica", "150 cred. o 57 cred BP"),
        course("FPTSP14", "Proyecto de Ingeniería", "150 cred. o 57 cred BP"),
        course("FGE", "Formacion General Electiva"),
      ],
    ],
  },
  {
    id: "mecanica",
    name: "Ingeniería Mecánica",
    approval: "Aprobado en marzo 2026",
    updatedAt: "Marzo 2026",
    periods: [
      ...mecanicaFirstPeriods,
      [
        course("BPTM03", "Matemáticas III", "BPTM02"),
        course("BPTFI02", "Física II", "BPTFI01+BPTM02"),
        course("BPTEN02", "Termodinamica I", "BPTFI01"),
        course("BPTPI02", "Mecánica I", "BPTFI01"),
        course("FBTHE11", "Vzla. Identidad y Contexto"),
      ],
      [
        course("BPTM04", "Matemáticas IV", "BPTM03"),
        course("BPTFI03", "Física III", "BPTFI02"),
        course("BPTEN07", "Termodinamica II", "BPTEN02"),
        course("BPTPI03", "Mecánica II", "BPTPI02"),
        course("BPTPI04", "Mecánica de Sólidos I", "BPTPI02"),
      ],
      [
        course("BPTM11", "Ecuaciones Diferenciales", "BPTM04"),
        course("BPTFI04", "Laboratorio de Física", "BPTFI03", { l: 4 }),
        course("BPTMI06", "Estadistica para Ingenieros I", "BPTM02"),
        course("BPTEN14", "Mecánica de Fluidos I", "BPTM04"),
        course("BPTPI05", "Mecánica de Sólidos II", "BPTPI04"),
      ],
      [
        course("BPTM05", "Matemáticas V", "BPTM04"),
        course("BPTEN03", "Electromecánica", "BPTFI03"),
        course("BPTPI01", "Representacion de Conj. Mecanicos", "BPTPI07"),
        course("BPTEN15", "Mecánica de Fluidos II", "BPTEN14"),
        course("BPTEN13", "Transferencia de Calor", "BPTEN02+BPTEN14"),
      ],
      [
        course("FPTEN05", "Lab. de Fluidos y Calor", "BPTEN13", { l: 4 }),
        course("BPTPI06", "Materiales", "BPTPI04", { a: 3, ps: 1 }),
        course("FPTEN22", "Instrumentación y Control", "BPTPI04", { a: 3, ps: 1 }),
        course("FGE", "Formacion General Electiva"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTPI01", "Diseno de Elem. de Maquinas I", "BPTPI01+BPTPI05"),
        course("FPTEN11", "Turbomaquinas", "BPTEN07+BPTEN15"),
        course("FPTPI06", "Procesos de Fabricacion I", "BPTPI06"),
        course("FPTPI02", "Mantenimiento", "BPTMI06"),
        course("FPTSP22", "Taller de Trabajo de Grado", "120 cred. o 57 cred BP", { a: 2, ps: 2, credits: 3 }),
      ],
      [
        course("FPTPI03", "Diseno de Elem. de Maquinas II", "FPTPI01"),
        course("FPTPI04", "Vibraciones", "BPTPI03"),
        course("FPTPI07", "Procesos de Fabricacion II", "FPTPI06"),
        course("FPS", "Seminario Profesional I", "120 cred.", { a: 2, ps: 2, credits: 3 }),
        course("FPTPI17", "Lab. de Ensayos Mecanicos", "BPTPI06"),
      ],
      [
        course("FPTPI18", "Diseno Conceptual", "FPTPI03"),
        course("FPTPI05", "Laboratorio de Vibraciones", "FPTPI04", { l: 4 }),
        course("FPTEN28", "Conversión y Almacen. de Energía", "75 créditos"),
        course("FPS", "Seminario Profesional II", "120 cred."),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTCS16", "Ingeniería Ambiental", "150 cred. o 57 cred BP"),
        course("FPTSP15", "Ingeniería Económica", "150 cred. o 57 cred BP"),
        course("FPTSP14", "Proyecto de Ingeniería", "150 cred. o 57 cred BP"),
        course("FGE", "Formacion General Electiva"),
        course("FGE", "Formacion General Electiva"),
      ],
    ],
  },
  {
    id: "electrica",
    name: "Ingeniería Eléctrica",
    approval: "Flujograma de componentes educativos obligatorios",
    updatedAt: "2026",
    periods: [
      [
        course("FBTMM01", "Matemática Básica"),
        course("FBTPS03", "Introducción a la Ingeniería"),
        course("FBTPS04", "Pensamiento Computacional"),
        course("FBTEM01", "Competencias para Emprender"),
        course("FBTLI14", "Ingles IV"),
      ],
      [
        course("BPTM01", "Matemáticas I", "FBTMM01"),
        course("BPTPI07", "Diseno asistido por Computador"),
        course("BPTQI21", "Química General", "FBTMM01"),
        course("FBTHE05", "Investigación y Sustentabilidad"),
        course("FBTLI15", "Ingles V", "FBTLI14"),
      ],
      [
        course("BPTM02", "Matemáticas II", "BPTM01"),
        course("BPTFI01", "Física I", "BPTM01"),
        course("BPTQI22", "Laboratorio de Química General", "BPTQI21", { l: 4 }),
        course("BPTPS05", "Algoritmos y Programación", "FBTPS04"),
        course("FBTEM02", "Ideas Emprendedoras"),
      ],
      [
        course("BPTM03", "Matemáticas III", "BPTM02"),
        course("BPTFI02", "Física II", "BPTFI01+BPTM02"),
        course("BPTEN03", "Redes electricas I", "BPTFI01"),
        course("BPTEN02", "Termodinamica I", "BPTFI01"),
        course("FBTHE11", "Venezuela Identidad y Contexto"),
      ],
      [
        course("BPTM04", "Matemáticas IV", "BPTM03"),
        course("BPTFI03", "Física III", "BPTFI02"),
        course("BPTEN05", "Redes electricas II", "BPTEN03"),
        course("BPTEN12", "Arquitectura del Computador", "BPTPS05"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("BPTM11", "Ecuaciones Diferenciales", "BPTM04"),
        course("BPTFI04", "Laboratorio de Física", "BPTFI03", { l: 4 }),
        course("FPTEN01", "Electrónica Analógica I", "BPTEN03"),
        course("BPTMI06", "Estadistica para Ingenieros I", "BPTM03"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("BPTM05", "Matemáticas V", "BPTM04"),
        course("FPTEN03", "Electromecánica", "BPTFI03"),
        course("FPTEN04", "Electrónica Analógica II", "FPTEN01"),
        course("FPTEN06", "Maquinas electricas I", "BPTEN05", { a: 2, ps: 2 }),
        course("BPTM10", "Matemáticas avanzadas para Ing", "BPTM04"),
      ],
      [
        course("FPTEN11", "Analisis de Senales", "BPTM10+BPTEN03"),
        course("FPTEN09", "Maquinas electricas II", "FPTEN06", { a: 2, ps: 2 }),
        course("FPTEN29", "Fundamentos de Energias Renovables", "75 CR"),
        course("FPTEN30", "Eficiencia energética", "75 CR"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTEN22", "Instrumentacion y control", "BPTFI04"),
        course("FPTEN19", "Control", "BPTEN11"),
        course("FPTEN24", "Comunicaciones", "BPTEN11"),
        course("BPTEN10", "Teoría electromagnética", "BPTM05+BPTFI03"),
        course("FPTSP22", "Taller de Trabajo de Grado", "120 cr o 57 cr BP", { a: 2, ps: 2, credits: 3 }),
      ],
      [
        course("FPTEN23", "Sistemas de Redes", "BPTFI02 o 57 BP"),
        course("FPTEN31", "Automatización y control", "FPTEN22", { a: 2, ps: 2 }),
        course("FPTEN26", "Procesamiento Digital de Senales", "BPTEN11 o 57 cr BP"),
        course("FPTEN10", "Sistemas de Potencia I", "FPTEN06 o 57 cr BP", { a: 3, ps: 1 }),
        course("FPS", "Seminario Profesional", "120 cr", { a: 2, ps: 2, credits: 3 }),
      ],
      [
        course("FPTEN27", "Robótica Industrial", "BPTPS05"),
        course("FPTEN13", "Electrónica Industrial", "FPTEN04"),
        course("FPTEN28", "Conversión y almacenamiento de energía", "75 CR", { a: 2, ps: 2 }),
        course("FPTEN14", "Sistemas de Potencia II", "FPTEN10", { a: 3, ps: 1 }),
        course("FPS", "Seminario Profesional 2", "120 cr"),
      ],
      [
        course("FPTSP14", "Proyecto de Ingeniería", "150 cr o 57 cr BP"),
        course("FPTSP15", "Ingeniería Económica", "150 cr o 57 cr BP"),
        course("FPTCS16", "Ingeniería Ambiental", "150 cr o 57 cr BP"),
        course("FGE", "Formacion General Electiva"),
        course("FGE", "Formacion General Electiva"),
      ],
    ],
  },
  {
    id: "produccion",
    name: "Ingeniería de Producción",
    approval: "Flujograma de componentes educativos obligatorios",
    updatedAt: "2026",
    periods: [
      [
        course("FBTMM01", "Matemática Básica"),
        course("FBTPS03", "Introducción a la Ingeniería"),
        course("FBTPS04", "Pensamiento Computacional"),
        course("FBTEM01", "Competencias para Emprender"),
        course("FBTLI14", "Ingles IV"),
      ],
      [
        course("BPTM01", "Matemáticas I", "FBTMM01"),
        course("BPTPI07", "Diseno Asistido por Computador"),
        course("BPTQI21", "Química General", "FBTMM01"),
        course("FBTHE05", "Investigación y Sustentabilidad"),
        course("FBTLI15", "Ingles V", "FBTLI14"),
      ],
      [
        course("BPTM02", "Matemáticas II", "BPTM01"),
        course("BPTFI01", "Física I", "BPTM01"),
        course("BPTQI22", "Laboratorio de Química General", "BPTQI21", { l: 4 }),
        course("FBTEM02", "Ideas emprendedoras"),
        course("BPTPS05", "Algoritmos y Programación", "FBTPS04"),
      ],
      [
        course("BPTM03", "Matemáticas III", "BPTM02"),
        course("BPTFI02", "Física II", "BPTFI01+BPTM02"),
        course("BPTEN02", "Termodinamica I", "BPTFI01"),
        course("BPTPI02", "Mecánica I", "BPTFI01"),
        course("FBTHE11", "Venezuela Identidad y Contexto"),
      ],
      [
        course("BPTM04", "Matemáticas IV", "BPTM03"),
        course("BPTFI03", "Física III", "BPTFI02"),
        course("BPTEN01", "Balance de Masa y Energia I", "BPTEN02+BPTQI21"),
        course("BPTPI04", "Mecánica de sólidos I", "BPTPI02"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("BPTM11", "Ecuaciones Diferenciales", "BPTM04"),
        course("BPTFI04", "Laboratorio de Física", "BPTFI03", { l: 4 }),
        course("BPTMI06", "Estadistica para Ingenieros I", "BPTM02"),
        course("BPTEN14", "Mecánica de fluidos I", "BPTM04"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("BPTM05", "Matemáticas V", "BPTM04"),
        course("FPTEN03", "Electromecánica", "BPTFI03"),
        course("BPTMI07", "Estadistica para Ingenieros II", "BPTMI06+BPTM03"),
        course("FPTSP17", "Optimización I", "BPTM11"),
        course("BPTPI08", "Sistemas de producción", "BPTMI06"),
      ],
      [
        course("FPTPI09", "Gestion de la cadena de suministro I", "FPTSP17"),
        course("BPTMK01", "Mercadeo", "90 créditos"),
        course("BPTPI06", "Materiales", "BPTPI04", { a: 3, ps: 1 }),
        course("FPTSP19", "Optimización II", "FPTSP17"),
        course("FPTEN22", "Instrumentación y Control", "BPTPI04"),
      ],
      [
        course("FPTPI12", "Gestion de la cadena de suministro II", "FPTPI09"),
        course("FPTMI21", "Modelos estocásticos", "BPTMI06"),
        course("FPTPI02", "Mantenimiento", "BPTMI06"),
        course("FPTSP22", "Taller de trabajo de grado", "120 cred. o 57 cred. BP", { a: 2, ps: 2 }),
        course("FPTPI06", "Procesos de Fabricacion I", "BPTPI06"),
      ],
      [
        course("FPTSP20", "Simulación", "BPTMI06"),
        course("FPTPI16", "Inteligencia de Negocios", "FPTPI09"),
        course("FPTPI10", "Aseguramiento de la calidad", "BPTMI06 o 57 cred. BP"),
        course("FPS", "Seminario Profesional", "120 créditos"),
        course("FGE", "Formacion General Electiva"),
      ],
      [
        course("FPTPI13", "Productividad y medición del trabajo", "BPTPI08+FPTPI06 o 57 créditos BP"),
        course("FPTPI14", "Planificación y control de la producción", "BPTPI08+FPTPI06 o 57 créditos BP"),
        course("FPTPI15", "Plantas Industriales", "BPTPI06 o 57 créditos BP"),
        course("FPTEN27", "Robótica Industrial", "BPTPS05"),
        course("FPS2", "Seminario Profesional", "120 créditos"),
      ],
      [
        course("FPTCS16", "Ingeniería ambiental", "150 créditos o 57 créditos BP"),
        course("FPTSP14", "Proyectos de ingeniería", "150 créditos o 57 créditos BP"),
        course("FPTSP15", "Ingeniería económica", "150 créditos o 57 créditos BP"),
        course("FGE", "Formacion General Electiva"),
        course("FGE", "Formacion General Electiva"),
      ],
    ],
  },
  {
    id: "quimica",
    name: "Ingeniería Química",
    approval: "Flujograma de componentes educativos obligatorios",
    updatedAt: "2026",
    periods: [
      [
        course("FBTMM01", "Matemática Básica"),
        course("FBTPS03", "Introducción a la Ingeniería"),
        course("FBTPS04", "Pensamiento Computacional"),
        course("FBTEM01", "Competencias para Emprender"),
        course("FBTLI14", "Ingles IV", "FBTLI13"),
      ],
      [
        course("BPTM01", "Matemáticas I", "FBTMM01"),
        course("BPTPI07", "Diseno Asistido por Computador"),
        course("FBTHE05", "Investigación y Sustentabilidad"),
        course("BPTQI21", "Química General", "FBTMM01"),
        course("FBTLI15", "Ingles V", "FBTLI14"),
      ],
      [
        course("BPTM02", "Matemáticas II", "BPTM01"),
        course("BPTFI01", "Física I", "BPTM01"),
        course("FBTEM02", "Ideas Emprendedoras"),
        course("BPTQI23", "Química General II", "BPTQI21"),
        course("BPTQI22", "Laboratorio de Química General I", "BPTQI21", { l: 4 }),
      ],
      [
        course("BPTM03", "Matemáticas III", "BPTM02"),
        course("BPTFI02", "Física II", "BPTFI01+BPTM02"),
        course("BPTEN02", "Termodinamica I", "BPTFI01"),
        course("BPTPS05", "Algoritmos y Programación", "FBTPS04"),
        course("BPTQI01", "Laboratorio de Química General II", "BPTQI23+BPTQI22", { l: 8 }),
      ],
      [
        course("BPTM04", "Matemáticas IV", "BPTM03"),
        course("BPTFI03", "Física III", "BPTFI02"),
        course("BPTEN01", "Balances de Masa y Energia I", "BPTEN02+BPTQI21"),
        course("BPTEN16", "Métodos Numéricos para Ing. Química", "BPTPS05+BPTMI02"),
        course("BPTQI11", "Química Orgánica I", "BPTQI23"),
      ],
      [
        course("BPTM11", "Ecuaciones Diferenciales", "BPTM04"),
        course("BPTFI04", "Laboratorio de Física", "BPTFI03", { l: 4 }),
        course("BPTEN04", "Balances de Masa y Energia II", "BPTEN01+BPTEN16"),
        course("BPTEN14", "Mecánica de Fluidos I", "BPTM04"),
        course("BPTQI15", "Química Orgánica II", "BPTQI11"),
      ],
      [
        course("BPTM05", "Matemáticas V", "BPTM04"),
        course("FBTHE11", "Venezuela Identidad y Contexto"),
        course("BPTEN09", "Termodinamica II", "BPTEN04"),
        course("BPTEN13", "Transferencia de Calor", "BPTEN02+BPTEN14"),
        course("BPTQI02", "Laboratorio de Química Orgánica", "BPTQI15+BPTQI01", { l: 4 }),
      ],
      [
        course("BPTMI06", "Estadistica para Ingenieros I", "BPTM02"),
        course("FGE", "Formacion General Electiva"),
        course("BPTQI06", "Fisicoquímica", "BPTFI03+BPTEN09"),
        course("FPTEN16", "Transferencia de Masa", "BPTEN13+BPTEN09"),
        course("FPTEN05", "Laboratorio de Fluidos y Calor", "BPTEN13", { l: 4 }),
      ],
      [
        course("FPTSP22", "Taller de Trabajo de Grado", "120 cred. o 57 cred. BP", { a: 2, ps: 2 }),
        course("FGE", "Formacion General Electiva"),
        course("FPTEN08", "Reactores I", "BPTQI06"),
        course("FPTEN17", "Procesos de Separación I", "FPTEN16"),
        course("BPTPI08", "Ciencia e Ingeniería de los Materiales", "BPTQI11", { a: 3, l: 1 }),
      ],
      [
        course("FPTEN22", "Instrumentación y Control", "BPTFI04"),
        course("FPS", "Seminario Profesional", "120 cred."),
        course("FPTEN08", "Reactores II"),
        course("FPTEN18", "Procesos de Separación II", "FPTEN16"),
        course("FPTQI01", "Laboratorio de Fisicoquímica", "BPTQI06+BPTQI02", { l: 12 }),
      ],
      [
        course("FPTEN34", "Control de Procesos IQ", "FPTEN22+BPTEN16"),
        course("FGE", "Formacion General Electiva"),
        course("FPTEN17", "Diseno de Procesos Quimicos", "FPTEN17"),
        course("FPTEN20", "Laboratorio de Ingeniería Química", "FPTEN17+FPTEN18", { l: 4 }),
        course("FPTPI10", "Aseguramiento de la Calidad", "BPTMI06 o 57 cred. BP"),
      ],
      [
        course("FPTCS16", "Ingeniería Ambiental", "150 cred. o 57 cred. BP"),
        course("FGE", "Formacion General Electiva"),
        course("FGE", "Formacion General Electiva"),
        course("FPTSP14", "Proyectos de Ingeniería", "150 cred. o 57 créditos BP"),
        course("FPTSP15", "Ingeniería Económica", "150 créditos o 57 créditos BP"),
      ],
    ],
  },
];

function course(code, name, prereq = "", overrides = {}) {
  return {
    code,
    name,
    prereq,
    status: prereq ? "Pendiente" : "Pendiente",
    credits: overrides.credits ?? 3,
    hours: {
      a: overrides.a ?? 4,
      ps: overrides.ps ?? 0,
      l: overrides.l ?? 0,
      aa: overrides.aa ?? 4,
    },
  };
}
